##################################################################
# ✨ Automatically solved by GitHub Copilot and atcoder-tools ✨ #
##################################################################

# This program was automatically generated by
# [GitHub Copilot](https://copilot.github.com/) and
# [atcoder-tools](https://github.com/kyuridenamida/atcoder-tools).
#
# For the concern of the copyright infringement by GitHub Copilot,
# please refer the following article.
#
# https://docs.github.com/en/github/copilot/research-recitation
#
# If you really think your copyright is being affected by this
# submission, please contact me at `hakatasiloving@gmail.com`.

# (c) 2021 Koki Takahashi
# I license this program under the terms where the requirements of 
# the related license agreement are met and satisfied.

{{ code }}

# Execution log
'''
{{ execution_log }}
## Candidates Summary

{% for candidate in candidates %}
### Candidate {{ loop.index }}

{{ candidate }}

{% endfor %}
### Candidate chosen for this submission

Candidate {{ choice + 1 }}
'''
