#################################################################
# ✨ Automatically solved by OpenAI Codex and atcoder-tools ✨ #
#################################################################

# This program was automatically generated by
# [OpenAI Codex](https://openai.com/blog/openai-codex/) and
# [atcoder-tools](https://github.com/kyuridenamida/atcoder-tools).
#
# For the concern of the copyright infringement by OpenAI Codex,
# please refer the following article.
#
# https://docs.github.com/en/github/copilot/research-recitation
#
# If you really think your copyright is being affected by this
# submission, please contact me at `hakatasiloving@gmail.com`.

# (c) 2021 Koki Takahashi
# This program is licensed under the terms by where the requirements
# of the related license agreement are met and satisfied.

{{ code }}

# Execution log
'''
{{ execution_log }}
## Candidates Summary

{% for candidate in candidates %}
### Candidate {{ loop.index }}

{{ candidate }}

{% endfor %}
### Candidate chosen for this submission

Candidate {{ choice + 1 }}
'''
